name: Publish to WinGet
on:
  release:
    types: [released]

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: vedantmgoyal2009/winget-releaser@v2
        with:
          identifier: marchellodev.Sharik
          token: ${{ secrets.WINGET_TOKEN }}
